version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      # persist data between app starts
      - ${PWD}/bank_db/:/var/lib/postgresql/data/
      # initialize the database when it doesn't already exist
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql
